version: '3.7'

services:
  metaheuristics:
    image: pmorski/metaheuristics
    env:
      - METAHEURISTIC_TYPE=GENETIC_TTP1
      # - METAHEURISTIC_TYPE=TABU_SEARCH_TTP1
      # - METAHEURISTIC_TYPE=ANNEALING_TTP1
    volumes:
      - "./problemInput.ttp:/metaheuristics/data/problemInput.ttp"
      - "./algInput.txt:/metaheuristics/data/algInput.txt"
      - "./output.csv:/metaheuristics/data/output.csv"
